"use client";

import React from "react";
import { resolveDonationQr, type DonationQrSources } from "@/lib/domain/qrCode";
import { useDonationQrConfig } from "@/components/providers/DonationQrProvider";

/**
 * The DuitNow QR panel shown on every public donation surface.
 *
 * This markup previously existed twice — the same twenty hand-placed <rect>
 * elements in `DonationWidget` and in `SponsorshipModal` — so wiring a real QR
 * into one would have silently left the other showing a decorative fake. There
 * is one copy now, and both surfaces render it.
 */

interface DonationQrPanelProps extends DonationQrSources {
  /** Localised "scan with your banking app" line. */
  instructions: string;
  /** Tighter spacing for use inside the sponsorship modal. */
  compact?: boolean;
  className?: string;
}

/**
 * Shelter-level sources come from `DonationQrProvider` unless a caller passes
 * them explicitly. The admin preview relies on that override to show unsaved
 * form values, which is the whole point of previewing before committing.
 */
function useResolvedSources(props: DonationQrPanelProps) {
  const config = useDonationQrConfig();
  return {
    petCustomQrUrl: props.petCustomQrUrl,
    petName: props.petName,
    shelterQrUrl: props.shelterQrUrl ?? config.duitNowQrUrl,
    paymentPayload: props.paymentPayload ?? config.paymentPayload,
  };
}

/**
 * The decorative stand-in used when the shelter has configured neither a QR
 * image nor a payment payload. It is not a scannable code and is marked
 * presentational so screen readers do not announce it as one.
 */
function PlaceholderQr() {
  return (
    <svg viewBox="0 0 100 100" className="w-full h-full" aria-hidden="true" focusable="false">
      <rect x="0" y="0" width="30" height="30" fill="#18181b" />
      <rect x="5" y="5" width="20" height="20" fill="white" />
      <rect x="10" y="10" width="10" height="10" fill="#18181b" />

      <rect x="70" y="0" width="30" height="30" fill="#18181b" />
      <rect x="75" y="5" width="20" height="20" fill="white" />
      <rect x="80" y="10" width="10" height="10" fill="#18181b" />

      <rect x="0" y="70" width="30" height="30" fill="#18181b" />
      <rect x="5" y="75" width="20" height="20" fill="white" />
      <rect x="10" y="80" width="10" height="10" fill="#18181b" />

      <rect x="40" y="10" width="10" height="10" fill="#18181b" />
      <rect x="55" y="15" width="10" height="10" fill="#18181b" />
      <rect x="35" y="35" width="30" height="30" fill="#ed008c" />
      <rect x="42" y="42" width="16" height="16" fill="white" />
      <rect x="46" y="46" width="8" height="8" fill="#ed008c" />
      <rect x="70" y="45" width="10" height="10" fill="#18181b" />
      <rect x="45" y="75" width="10" height="10" fill="#18181b" />
      <rect x="65" y="75" width="25" height="15" fill="#18181b" />
    </svg>
  );
}

export function DonationQrPanel(props: DonationQrPanelProps) {
  const { instructions, compact = false, className = "" } = props;
  const resolved = resolveDonationQr(useResolvedSources(props));

  const frameSize = compact ? "w-36 h-36" : "w-40 h-40";
  const titleSize = compact ? "text-[11px]" : "text-xs";
  const captionSize = compact ? "text-[10px]" : "text-xs";
  const noteSize = compact ? "text-[9px]" : "text-[10px]";

  return (
    <div
      className={`border-2 border-[#ed008c] bg-white text-zinc-900 ${
        compact ? "p-4" : "p-5"
      } rounded-xl flex flex-col items-center justify-center text-center shadow-sm ${className}`}
    >
      <div
        className={`${titleSize} font-extrabold uppercase tracking-widest text-[#ed008c] mb-0.5`}
      >
        DuitNow QR
      </div>
      <div className="text-[10px] text-zinc-600 font-semibold mb-2.5">
        National QR Standard (PayNet Malaysia)
      </div>

      <div
        className={`${frameSize} border border-zinc-300 p-2 bg-white flex items-center justify-center relative rounded-md`}
      >
        {resolved.kind === "generated" ? (
          // Generated by `renderQrSvg` from our own module matrix — no caller
          // text reaches the markup, so there is nothing to sanitise here.
          <span
            className="w-full h-full [&>svg]:w-full [&>svg]:h-full"
            dangerouslySetInnerHTML={{ __html: resolved.svg }}
          />
        ) : resolved.kind === "placeholder" ? (
          <PlaceholderQr />
        ) : (
          // Deliberately a plain <img>, not next/image. Two reasons: the
          // optimizer would re-encode the code, and lossy artefacts soften the
          // module edges a scanner thresholds on; and next/image gates remote
          // hosts on `images.remotePatterns`, which would silently break a QR
          // hosted anywhere an admin happens to paste. The URL is restricted to
          // /uploads/ or https by `isSafeQrImageUrl` before it reaches here.
          // eslint-disable-next-line @next/next/no-img-element
          <img
            src={resolved.imageUrl}
            alt={`DuitNow QR code for ${resolved.caption}`}
            className="absolute inset-0 size-full object-contain p-1"
          />
        )}
      </div>

      <div className={`${captionSize} font-bold text-zinc-800 mt-2.5`}>{resolved.caption}</div>

      {resolved.isPetSpecific && (
        <div className="mt-1 inline-block rounded-full bg-[#ed008c]/10 px-2 py-0.5 text-[9px] font-bold uppercase tracking-wide text-[#ed008c]">
          Dedicated fund drive
        </div>
      )}

      <div className={`${noteSize} text-zinc-500 font-mono mt-0.5`}>{instructions}</div>

      {resolved.kind === "placeholder" && (
        <div className={`${noteSize} text-amber-700 font-semibold mt-1`}>
          Sample image — no QR code has been configured yet.
        </div>
      )}
    </div>
  );
}
