/**
 * GET    /api/v1/products/{productId}
 * PATCH  /api/v1/products/{productId}
 * DELETE /api/v1/products/{productId}
 *
 * One route, one resource, one response shape. Compare with the Approach A handler,
 * which had to sniff the format of its own path parameter to decide what it was
 * returning.
 *
 * In the real app the context is typed with the generated helper:
 *
 *   import type { NextRequest } from "next/server";
 *   export async function GET(req: NextRequest, ctx: RouteContext<'/api/v1/products/[productId]'>)
 *
 * `RouteContext` is generated by `next dev` / `next build` / `next typegen` from the
 * actual route tree, so a typo in the route literal is a compile error. This file spells
 * the type out because it lives outside the app directory.
 */

import { z } from "zod";
import { problem, fieldIssues, notFound } from "../../../../../problem";
import {
  enforceIfMatch,
  etagFor,
  isNotModified,
  notModifiedResponse,
} from "../../../../../preconditions";
import {
  PRODUCT_STATUSES,
  authenticate,
  getProductRepository,
  unauthenticated,
  forbidden,
} from "../../../../../runtime";

interface Context {
  params: Promise<{ productId: string }>;
}

/**
 * Single resources are `private` but revalidatable: the ETag makes a repeat read a
 * cheap 304 rather than a full body transfer. This is the differentiated cache policy
 * that Approach A's polymorphic route could not express, because the same handler also
 * had to serve a volatile collection.
 */
const ENTITY_CACHE_CONTROL = "private, max-age=0, must-revalidate";

/**
 * Opaque prefixed identifiers, per rule N2. Validating the shape here means a malformed
 * id is a 400 before it ever reaches the database — and, more to the point, it makes the
 * ambiguity that motivated Approach A structurally impossible: `prod_…` can never be
 * mistaken for a category slug.
 */
const ProductId = z
  .string()
  .regex(/^prod_[0-9A-HJKMNP-TV-Z]{26}$/, "Must be a product id of the form prod_<ULID>.");

export async function GET(request: Request, context: Context): Promise<Response> {
  const instance = new URL(request.url).pathname;

  const principal = await authenticate(request);
  if (!principal) return unauthenticated(instance);
  if (!principal.scopes.includes("catalog:read")) {
    return forbidden("catalog:read", instance);
  }

  const { productId } = await context.params;
  const id = ProductId.safeParse(productId);
  if (!id.success) {
    return problem("invalid_query", {
      detail: "The product id in the path is malformed.",
      instance,
      errors: fieldIssues(id.error.issues),
    });
  }

  // Tenant scoping happens inside the query. A row belonging to another tenant comes
  // back as null and is reported as 404, never 403 — see notFound() for why.
  const product = await getProductRepository().find(principal.tenantId, id.data);
  if (!product) return notFound("product", id.data, instance);

  const etag = await etagFor(`${product.id}:${product.version}`);
  if (isNotModified(request, etag)) {
    return notModifiedResponse(etag, ENTITY_CACHE_CONTROL);
  }

  return new Response(JSON.stringify(product), {
    status: 200,
    headers: {
      "Content-Type": "application/json; charset=utf-8",
      "Cache-Control": ENTITY_CACHE_CONTROL,
      ETag: etag,
    },
  });
}

const PatchProduct = z
  .strictObject({
    name: z.string().min(1).max(200).optional(),
    category_id: z.string().min(1).optional(),
    brand_id: z.string().min(1).optional(),
    status: z.enum(PRODUCT_STATUSES).optional(),
    price: z.number().nonnegative().optional(),
  })
  .refine((patch) => Object.keys(patch).length > 0, {
    message: "Provide at least one field to change.",
  });

export async function PATCH(request: Request, context: Context): Promise<Response> {
  const instance = new URL(request.url).pathname;

  const principal = await authenticate(request);
  if (!principal) return unauthenticated(instance);
  if (!principal.scopes.includes("catalog:write")) {
    return forbidden("catalog:write", instance);
  }

  const { productId } = await context.params;
  const id = ProductId.safeParse(productId);
  if (!id.success) {
    return problem("invalid_query", {
      detail: "The product id in the path is malformed.",
      instance,
      errors: fieldIssues(id.error.issues),
    });
  }

  const current = await getProductRepository().find(principal.tenantId, id.data);
  if (!current) return notFound("product", id.data, instance);

  // Optimistic concurrency is mandatory on writes: 428 if the client did not send
  // If-Match, 412 if it sent a stale one. Two integrators patching the same product
  // can no longer silently overwrite each other.
  const etag = await etagFor(`${current.id}:${current.version}`);
  const precondition = enforceIfMatch(request, etag, instance);
  if (precondition) return precondition;

  const parsed = PatchProduct.safeParse(await request.json().catch(() => null));
  if (!parsed.success) {
    return problem("invalid_body", {
      detail: "One or more fields were rejected.",
      instance,
      errors: fieldIssues(parsed.error.issues),
    });
  }

  const updated = await getProductRepository().update(
    principal.tenantId,
    id.data,
    parsed.data
  );

  return new Response(JSON.stringify(updated), {
    status: 200,
    headers: {
      "Content-Type": "application/json; charset=utf-8",
      "Cache-Control": "no-store",
      ETag: await etagFor(`${updated.id}:${updated.version}`),
    },
  });
}
